In [15]:
import numpy as np

In [18]:
my_list = [1,2,3]
arr = np.array(my_list)

In [19]:
arr

array([1, 2, 3])

In [22]:
# start,stop,step
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [37]:
# start,stop, how many points you want evenly spaced between
np.linspace(0,11,10)


array([ 0.        ,  1.22222222,  2.44444444,  3.66666667,  4.88888889,
        6.11111111,  7.33333333,  8.55555556,  9.77777778, 11.        ])

In [50]:
# returns back a random number
np.random.randint(0,10, (3,3))

array([[3, 4, 7],
       [6, 5, 0],
       [1, 5, 0]])

In [51]:
np.random.normal(10)

10.511331211099632

In [52]:
#  When you set the seed (every time), 
# it does the same thing every time, giving you the same numbers.
np.random.seed(101)

In [56]:
val = np.random.randint(0,100,10)

In [57]:
np.max(val)

99

In [58]:
np.min(val)

0

In [59]:
np.mean(val)

61.9

In [61]:
# returns index position of highest value
arr.argmax()

2

In [62]:
arr

array([1, 2, 3])

In [63]:
val

array([76, 95, 87,  0, 73,  8, 62, 36, 83, 99])

In [66]:
# reshapes into 2 X 5 array
val.reshape(2,5)

array([[76, 95, 87,  0, 73],
       [ 8, 62, 36, 83, 99]])

In [67]:
mat = np.arange(0,100).reshape(10,10)

In [68]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [73]:
# Single element
mat[9,9]

99

In [78]:
# all rows and all col up to 1st 
mat[: , :1]

array([[ 0],
       [10],
       [20],
       [30],
       [40],
       [50],
       [60],
       [70],
       [80],
       [90]])

In [83]:
mat[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
mat[:, :]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [85]:
mat[:3, :3  ]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [91]:
# Masking
mat > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [90]:
my_filter = mat > 50
# returns values greater than 50
mat[my_filter]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])