In [1]:
import numpy as np

In [2]:
from sklearn.preprocessing import MinMaxScaler

In [3]:
rnd = np.random.randint(0,100,(10,2))

In [4]:
rnd

array([[62, 94],
       [64, 23],
       [59, 53],
       [64, 31],
       [54, 39],
       [23, 94],
       [88, 63],
       [15, 24],
       [86,  0],
       [40,  9]])

In [5]:
# scaling data to run into neural network
scaler_model = MinMaxScaler()

In [6]:
type(scaler_model)

sklearn.preprocessing.data.MinMaxScaler

In [7]:
# Fit model to data - Allows model to learn min and max for each column
scaler_model.fit(rnd)

/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


MinMaxScaler(copy=True, feature_range=(0, 1))

In [9]:
# Each column we took the max and divided against every number and the 
# results are what you see below
scaler_model.transform(rnd)

array([[0.64383562, 1.        ],
       [0.67123288, 0.24468085],
       [0.60273973, 0.56382979],
       [0.67123288, 0.32978723],
       [0.53424658, 0.41489362],
       [0.10958904, 1.        ],
       [1.        , 0.67021277],
       [0.        , 0.25531915],
       [0.97260274, 0.        ],
       [0.34246575, 0.09574468]])

In [10]:
# Here we do the same but in one step
# Based on the situtation, you wanna fit to your training data then transform
# to your test and training. Reason being is because you dont wanna assume or cheat
# your test data
scaler_model.fit_transform(rnd)

/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


array([[0.64383562, 1.        ],
       [0.67123288, 0.24468085],
       [0.60273973, 0.56382979],
       [0.67123288, 0.32978723],
       [0.53424658, 0.41489362],
       [0.10958904, 1.        ],
       [1.        , 0.67021277],
       [0.        , 0.25531915],
       [0.97260274, 0.        ],
       [0.34246575, 0.09574468]])

In [11]:
import pandas as pd

In [17]:
storage = pd.DataFrame(data=np.random.randint(0,100,(50,4)), columns=['f1',
                                                                    'f2',
                                                                    'f3',
                                                                    'labels'])

In [18]:
storage

f1  f2  f3  labels
0   91  50  58      79
1   52  75  93      30
2   44  90   4      44
3   73  86  18      46
4   66   2  32      19
5   83  25  35      65
6   95  30  25      46
7   94  36  15      32
8   67   2   3      63
9   39  27  88      52
10   3  36  27      73
11  47  49  63      15
12  59  87  24      73
13  13  65  17      52
14  11  38  64      30
15  39  21  73      41
16  95  37  98      61
17  76  13  59      87
18  52  98  41      74
19  30  89  13      66
20  89  84  69      32
21  91  16  67      65
22  24  74  98       3
23   5   5  58      76
24  55  54   3       7
25  67  16  17      10
26  28   7   5      70
27  43  83  96      11
28  39  56  88      21
29  42  41  45       2
30  70   9  86      69
31  43  19  69      93
32  79  95  75      40
33  58  74  13      60
34  54   7  18      67
35  88  99  45      61
36  25   2  35      47
37  67  45  55      65
38  90  54  56      16
39  85  89  14      28
40  19  78  67      80
41  90  73  39      37
42  50  39  63      52
43  78  89  14       5
44  85  47  58      84
45  10  46  21      34
46   2  50  33      49
47  32  27  46      54
48  66  56  70      72
49  35  33  56      73

In [22]:
# To split into training and test set

x = storage[['f1', 'f2', 'f3']]

In [23]:
y = storage['labels']

In [24]:
y

0     79
1     30
2     44
3     46
4     19
5     65
6     46
7     32
8     63
9     52
10    73
11    15
12    73
13    52
14    30
15    41
16    61
17    87
18    74
19    66
20    32
21    65
22     3
23    76
24     7
25    10
26    70
27    11
28    21
29     2
30    69
31    93
32    40
33    60
34    67
35    61
36    47
37    65
38    16
39    28
40    80
41    37
42    52
43     5
44    84
45    34
46    49
47    54
48    72
49    73
Name: labels, dtype: int64

In [25]:
from sklearn.model_selection import train_test_split

In [27]:
# We get the training and test sets
# we set the test_size to 33%. Usually a 70-30 split
# random-state: seed used by the random number generator

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)

In [30]:
X_train.shape

(33, 3)

In [32]:
X_test.shape

(17, 3)

In [33]:
y_test.shape

(17,)

In [35]:
y_train.shape

(33,)