In [3]:
import numpy as np
import tensorflow as tf

np.random.seed(101)
tf.set_random_seed(101)

In [6]:
rand_a = np.random.uniform(0,100, (5,5))

In [24]:
rand_b = np.random.uniform(0,100, (5,1))

In [25]:
rand_b

array([[97.5361127 ],
       [20.35276206],
       [29.90204097],
       [22.76558928],
       [ 4.81688854]])

In [26]:
a = tf.placeholder(tf.int32)

In [27]:
b = tf.placeholder(tf.int32)

In [28]:
add_op = a + b

In [29]:
mul_op = a * b

In [36]:
# matrix addition
# feed_dict = key is the placeholder. values are data that are filled by the placeholders
with tf.Session() as sess:
    add_result = sess.run(add_op , feed_dict = {a:rand_a, b:rand_b})
    print("the add result is {}".format(add_result))
    
    mul_result = sess.run(mul_op, feed_dict = {a:rand_a,b:rand_b})
    print("the mul result is {}".format(mul_result))
    

the add result is [[165 149 101 119 154]
 [ 32  70  33  25  37]
 [ 73 116 123  76  75]
 [ 85  54  33  27  85]
 [ 85  71  69  46  69]]
the mul result is [[6596 5044  388 2134 5529]
 [ 240 1000  260  100  340]
 [1276 2523 2726 1363 1334]
 [1386  704  242  110 1386]
 [ 324  268  260  168  260]]
