In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

1.3.0


In [3]:
# Tensor is an n-dimenional array
# The most basic kind is a constant
c1 = tf.constant("Hello")

In [4]:
c2 = tf.constant("World")

In [8]:
# with opens and closes our session for us
with tf.Session() as sess:
    result = sess.run(c1 + c2)

In [9]:
# the b in front means that its a byte literal
print(result)

b'HelloWorld'


In [10]:
a = tf.constant(10)

In [11]:
b = tf.constant(20)

In [12]:
type(a)

tensorflow.python.framework.ops.Tensor

In [13]:
a + b

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [14]:
with tf.Session() as sess:
    result = sess.run(a + b)

In [15]:
print(result)

30


In [16]:
fill_mat = tf.fill((3,3) , 10)

In [17]:
fill_mat

<tf.Tensor 'Fill:0' shape=(3, 3) dtype=int32>

In [19]:
my_zeroes = tf.zeros((3,3), 10)

In [21]:
my_ones = tf.ones((3,3))

In [22]:
myrandn = tf.random_normal((4,4), mean=0, stddev=1.0)

In [23]:
myrandunif = tf.random_uniform((4,4), minval = 0 , maxval = 10)

In [24]:
my_ops = [fill_mat, my_zeroes, my_ones, myrandn, myrandunif]

In [25]:
# creates an interactive session
sess = tf.InteractiveSession()

In [29]:
for ops in my_ops:
    print(sess.run(ops))
    print("\n")

[[10 10 10]
 [10 10 10]
 [10 10 10]]


[[False False False]
 [False False False]
 [False False False]]


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


[[ 1.9968582   0.4929767   0.17950833 -1.1470081 ]
 [-1.571342    0.6263687  -0.0106507  -0.01420481]
 [ 0.23437384 -0.62542075  0.01911293 -1.7454414 ]
 [ 0.7638646  -1.5897474   1.3695775   2.2629435 ]]


[[1.290518  3.6123896 7.6768923 1.8411493]
 [2.9951608 9.31566   9.60023   2.9267216]
 [3.2450092 8.017058  7.134138  4.2112064]
 [7.6540446 1.2567508 4.26522   1.9022441]]




In [30]:
mtrx = tf.constant([ [1,2] , [3,4]  ])

In [32]:
mtrx.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [33]:
mtrx2 = tf.constant( [ [10] , [100]  ] )

In [35]:
mtrx2.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [36]:
results = tf.matmul(mtrx, mtrx2)

In [37]:
results

<tf.Tensor 'MatMul:0' shape=(2, 1) dtype=int32>

In [38]:
results.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [39]:
sess.run(results)

array([[210],
       [430]], dtype=int32)

In [40]:
results.eval()

array([[210],
       [430]], dtype=int32)